//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCEL.DocUpload.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class All_Abb_Temp_Tables_Data
    {
        public int ABBDataId { get; set; }
        public Nullable<bool> IsDataTransfered { get; set; }
        public string Sponsor_Name { get; set; }
        public string Sponsor_Order_No_ { get; set; }
        public string Regd_No { get; set; }
        public string C_Customer_Name { get; set; }
        public string Customer_Mobile { get; set; }
        public string Customer_E_mail { get; set; }
        public string Customer_Address_1 { get; set; }
        public string Customer_Address_2 { get; set; }
        public Nullable<double> Customer_Pin_Code { get; set; }
        public string Customer_City { get; set; }
        public string Customer_State { get; set; }
        public string New_Prod__Group { get; set; }
        public string New_Prod_Type { get; set; }
        public string New_Brand { get; set; }
        public string New_Size { get; set; }
        public string Prod__Sr__No_ { get; set; }
        public string Model_No { get; set; }
        public string ABB_Plan_Name { get; set; }
        public string HSN_Code__For_ABB_Fees_ { get; set; }
        public Nullable<System.DateTime> Invoice_Date { get; set; }
        public string Invoice_No { get; set; }
        public string New_Price { get; set; }
        public Nullable<double> ABB_Fees { get; set; }
        public Nullable<double> ABB_Plan_Period__Months_ { get; set; }
        public string Order_Type { get; set; }
        public string Sponsor_Prog__code { get; set; }
        public string ABB_Price_Id { get; set; }
        public string Upload_Date___Time { get; set; }
        public Nullable<System.DateTime> Upload_Date { get; set; }
        public string Sponsor_Status { get; set; }
        public string Store_Code { get; set; }
        public string Store_Name { get; set; }
        public string Location { get; set; }
        public string Invoice_Image { get; set; }
        public string Mar_Com { get; set; }
        public string Approved { get; set; }
        public string ID { get; set; }
        public Nullable<double> Product_Net_Price__Incl_Of_GST_ { get; set; }
        public string Is_ABB_Payment_Done { get; set; }
        public string Payment_Remark { get; set; }
        public string Transaction_Id { get; set; }
        public string Order_Id { get; set; }
    }
}
