//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCEL.DocUpload.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVCAll_Call_AllocationsData
    {
        public int AllocationsDataId { get; set; }
        public Nullable<bool> IsDataTransfered { get; set; }
        public string EVC_Code { get; set; }
        public string EVC_BusinessName { get; set; }
        public string R__No_ { get; set; }
        public Nullable<double> Cust_PIN_Code { get; set; }
        public string Cust_City { get; set; }
        public string Prod_Group { get; set; }
        public string Type { get; set; }
        public string Actual_Prod_Qlty__at_time_of_QC_ { get; set; }
        public Nullable<double> Actual_EVC_Amount_As_Per_QC { get; set; }
        public string Allocation_Status { get; set; }
        public string Address_Line_1 { get; set; }
        public string Address_Line_2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string EVC_Address { get; set; }
        public string Invoice_No { get; set; }
        public Nullable<System.DateTime> Invoice_Date { get; set; }
        public string Proof_Of_Delivery { get; set; }
        public string Errorlog { get; set; }
    }
}
