//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCEL.DocUpload.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Map_ServicePartnerCityState
    {
        public int Map_ServicePartnerCityStateId { get; set; }
        public Nullable<int> ServicePartnerId { get; set; }
        public Nullable<int> PincodeId { get; set; }
        public Nullable<bool> IsPrimaryPincode { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string ListOfPincodes { get; set; }
    
        public virtual tblCity tblCity { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
        public virtual tblPinCode tblPinCode { get; set; }
        public virtual tblServicePartner tblServicePartner { get; set; }
        public virtual tblState tblState { get; set; }
    }
}
