//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCEL.DocUpload.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl247Around
    {
        public int Id { get; set; }
        public string partnerName { get; set; }
        public string orderID { get; set; }
        public string itemID { get; set; }
        public string product { get; set; }
        public string brand { get; set; }
        public string productType { get; set; }
        public string category { get; set; }
        public string subCategory { get; set; }
        public string name { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public string pincode { get; set; }
        public string city { get; set; }
        public string requestType { get; set; }
        public string paidByCustomer { get; set; }
        public Nullable<System.DateTime> deliveryDate { get; set; }
        public string TwoFourSevenAroundBooKingID { get; set; }
    }
}
