//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCEL.DocUpload.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblABBRegistration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblABBRegistration()
        {
            this.tblABBRedemptions = new HashSet<tblABBRedemption>();
            this.tblTransMasterABBPlanMasters = new HashSet<tblTransMasterABBPlanMaster>();
            this.tblCustomerFiles = new HashSet<tblCustomerFile>();
        }
    
        public int ABBRegistrationId { get; set; }
        public string ZohoABBRegistrationId { get; set; }
        public Nullable<int> BusinessUnitId { get; set; }
        public string RegdNo { get; set; }
        public string SponsorOrderNo { get; set; }
        public string CustFirstName { get; set; }
        public string CustLastName { get; set; }
        public string CustMobile { get; set; }
        public string CustEmail { get; set; }
        public string CustAddress1 { get; set; }
        public string CustAddress2 { get; set; }
        public string Location { get; set; }
        public string CustPinCode { get; set; }
        public string CustCity { get; set; }
        public string CustState { get; set; }
        public Nullable<int> NewProductCategoryId { get; set; }
        public Nullable<int> NewProductCategoryTypeId { get; set; }
        public Nullable<int> NewBrandId { get; set; }
        public string NewSize { get; set; }
        public string ProductSrNo { get; set; }
        public Nullable<int> ModelNumberId { get; set; }
        public string ABBPlanName { get; set; }
        public string HSNCode { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<decimal> NewPrice { get; set; }
        public Nullable<decimal> ABBFees { get; set; }
        public string OrderType { get; set; }
        public string SponsorProdCode { get; set; }
        public Nullable<int> ABBPriceId { get; set; }
        public Nullable<System.DateTime> UploadDateTime { get; set; }
        public Nullable<int> BusinessPartnerId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string YourRegistrationNo { get; set; }
        public string InvoiceImage { get; set; }
        public string ABBPlanPeriod { get; set; }
        public string NoOfClaimPeriod { get; set; }
        public Nullable<decimal> ProductNetPrice { get; set; }
        public Nullable<bool> OtherCommunications { get; set; }
        public Nullable<bool> FollowupCommunication { get; set; }
        public Nullable<int> StateId { get; set; }
        public string StoreCode { get; set; }
        public string StoreName { get; set; }
        public string NewProductCategoryName { get; set; }
        public string NewProductCategoryType { get; set; }
        public Nullable<bool> AbbApprove { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string StoreManagerEmail { get; set; }
        public string UploadImage { get; set; }
        public Nullable<bool> SponsorStatus { get; set; }
        public string MarCom { get; set; }
        public Nullable<bool> AbbReject { get; set; }
        public Nullable<bool> PaymentStatus { get; set; }
        public string OtherModelNo { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string EmployeeId { get; set; }
        public Nullable<decimal> DealerMargin { get; set; }
        public Nullable<decimal> BusinessUnitMargin { get; set; }
        public Nullable<decimal> BaseValue { get; set; }
        public Nullable<decimal> Cgst { get; set; }
        public Nullable<decimal> Sgst { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblABBRedemption> tblABBRedemptions { get; set; }
        public virtual tblBusinessPartner tblBusinessPartner { get; set; }
        public virtual tblProductCategory tblProductCategory { get; set; }
        public virtual tblProductType tblProductType { get; set; }
        public virtual tblExchangeOrderStatu tblExchangeOrderStatu { get; set; }
        public virtual tblExchangeOrderStatu tblExchangeOrderStatu1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTransMasterABBPlanMaster> tblTransMasterABBPlanMasters { get; set; }
        public virtual tblCustomerDetail tblCustomerDetail { get; set; }
        public virtual tblBusinessUnit tblBusinessUnit { get; set; }
        public virtual tblModelNumber tblModelNumber { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCustomerFile> tblCustomerFiles { get; set; }
    }
}
