//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCEL.DocUpload.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblABBPriceMaster
    {
        public int PriceMasterId { get; set; }
        public Nullable<int> BusinessUnitId { get; set; }
        public Nullable<int> ProductCatId { get; set; }
        public Nullable<int> ProductTypeId { get; set; }
        public Nullable<short> FeeTypeId { get; set; }
        public string Sponsor { get; set; }
        public string Product_Category { get; set; }
        public string Product_Sabcategory { get; set; }
        public Nullable<int> Price_Start_Range { get; set; }
        public Nullable<int> Price_End_Range { get; set; }
        public string Fee_Type { get; set; }
        public Nullable<decimal> Fees_Applicable_Amt { get; set; }
        public Nullable<decimal> Fees_Applicable_Percentage { get; set; }
        public Nullable<int> Plan_Period_in_Months { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<decimal> BusinessUnitMarginAmount { get; set; }
        public Nullable<decimal> BusinessUnitMarginPerc { get; set; }
        public Nullable<decimal> BusinessPartnerMarginAmount { get; set; }
        public Nullable<decimal> BusinessPartnerMarginPerc { get; set; }
        public Nullable<decimal> GSTExclusive { get; set; }
        public Nullable<decimal> GSTInclusive { get; set; }
        public Nullable<decimal> GstValueForNewProduct { get; set; }
    
        public virtual tblBusinessUnit tblBusinessUnit { get; set; }
        public virtual tblProductCategory tblProductCategory { get; set; }
        public virtual tblProductType tblProductType { get; set; }
    }
}
