//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCEL.DocUpload.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccessList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAccessList()
        {
            this.tblAccessList1 = new HashSet<tblAccessList>();
            this.tblRoleAccesses = new HashSet<tblRoleAccess>();
        }
    
        public int AccessListId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ActionName { get; set; }
        public string ActionURL { get; set; }
        public Nullable<int> ParentAccessListId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string SetIcon { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<bool> IsMenu { get; set; }
    
        public virtual tblCompany tblCompany { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAccessList> tblAccessList1 { get; set; }
        public virtual tblAccessList tblAccessList2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRoleAccess> tblRoleAccesses { get; set; }
    }
}
