//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCEL.DocUpload.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBusinessPartner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblBusinessPartner()
        {
            this.tblExchangeOrders = new HashSet<tblExchangeOrder>();
            this.tblVoucherVerfications = new HashSet<tblVoucherVerfication>();
            this.tblABBRegistrations = new HashSet<tblABBRegistration>();
            this.tblABBRedemptions = new HashSet<tblABBRedemption>();
            this.tblModelNumbers = new HashSet<tblModelNumber>();
            this.tblOrderBasedConfigs = new HashSet<tblOrderBasedConfig>();
            this.tblProductConditionLabels = new HashSet<tblProductConditionLabel>();
            this.tblPriceMasterMappings = new HashSet<tblPriceMasterMapping>();
            this.tblModelMappings = new HashSet<tblModelMapping>();
            this.tblModelMappings1 = new HashSet<tblModelMapping>();
            this.tblBPBURedemptionMappings = new HashSet<tblBPBURedemptionMapping>();
            this.tblBPBUAssociations = new HashSet<tblBPBUAssociation>();
            this.TblBPPincodeMappings = new HashSet<TblBPPincodeMapping>();
            this.tblUninstallationPrices = new HashSet<tblUninstallationPrice>();
            this.tblCouponMasters = new HashSet<tblCouponMaster>();
        }
    
        public int BusinessPartnerId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string StoreCode { get; set; }
        public string QRCodeURL { get; set; }
        public string QRImage { get; set; }
        public string ContactPersonFirstName { get; set; }
        public string ContactPersonLastName { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string Pincode { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public Nullable<int> BusinessUnitId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsABBBP { get; set; }
        public Nullable<bool> IsExchangeBP { get; set; }
        public string FormatName { get; set; }
        public Nullable<bool> IsDealer { get; set; }
        public string BPPassword { get; set; }
        public string AssociateCode { get; set; }
        public Nullable<bool> IsORC { get; set; }
        public Nullable<bool> IsDefferedSettlement { get; set; }
        public string LogoImage { get; set; }
        public Nullable<bool> IsOtpRequired { get; set; }
        public string SponsorName { get; set; }
        public string StoreType { get; set; }
        public string GSTNumber { get; set; }
        public string BankDetails { get; set; }
        public string AccountNo { get; set; }
        public string IFSCCode { get; set; }
        public Nullable<bool> PaymentToCustomer { get; set; }
        public string DashBoardImage { get; set; }
        public Nullable<bool> IsDefferedAbb { get; set; }
        public Nullable<bool> IsD2C { get; set; }
        public Nullable<bool> IsVoucher { get; set; }
        public Nullable<int> VoucherType { get; set; }
        public Nullable<bool> IsRedemptionSettelemtInstant { get; set; }
        public Nullable<int> cityId { get; set; }
        public Nullable<decimal> SweetenerBU { get; set; }
        public Nullable<decimal> SweetenerBP { get; set; }
        public Nullable<decimal> SweetenerDigi2l { get; set; }
        public string UPIId { get; set; }
        public Nullable<bool> IsDefaultPickupAddress { get; set; }
        public Nullable<bool> IsUnInstallationRequired { get; set; }
        public Nullable<bool> IsBarcodeReaderEnable { get; set; }
        public Nullable<bool> IsSrNumValidationEnable { get; set; }
        public Nullable<bool> IsCouponsAvailable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblExchangeOrder> tblExchangeOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblVoucherVerfication> tblVoucherVerfications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblABBRegistration> tblABBRegistrations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblABBRedemption> tblABBRedemptions { get; set; }
        public virtual tblCity tblCity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblModelNumber> tblModelNumbers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrderBasedConfig> tblOrderBasedConfigs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProductConditionLabel> tblProductConditionLabels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPriceMasterMapping> tblPriceMasterMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblModelMapping> tblModelMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblModelMapping> tblModelMappings1 { get; set; }
        public virtual tblBusinessUnit tblBusinessUnit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBPBURedemptionMapping> tblBPBURedemptionMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBPBUAssociation> tblBPBUAssociations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblBPPincodeMapping> TblBPPincodeMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUninstallationPrice> tblUninstallationPrices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCouponMaster> tblCouponMasters { get; set; }
    }
}
