//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCEL.DocUpload.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBusinessCustomer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblBusinessCustomer()
        {
            this.tblBookingItems = new HashSet<tblBookingItem>();
            this.tblCustomerCompanies = new HashSet<tblCustomerCompany>();
        }
    
        public int BusinessCustomerId { get; set; }
        public string ZohoId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public string PhoneNo { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Category { get; set; }
        public string Type { get; set; }
        public string Gender { get; set; }
        public string Mailing_Zip { get; set; }
        public string Mailing_Street { get; set; }
        public string Mailing_City { get; set; }
        public string Mailing_Country { get; set; }
        public string Mailing_State { get; set; }
        public string Other_Country { get; set; }
        public string Other_State { get; set; }
        public string Other_City { get; set; }
        public string Other_Street { get; set; }
        public string Other_Zip { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBookingItem> tblBookingItems { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCustomerCompany> tblCustomerCompanies { get; set; }
    }
}
