//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCEL.DocUpload.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBusinessTypeMapping
    {
        public int BusinessTypeMappingId { get; set; }
        public Nullable<int> BussinessCustomerId { get; set; }
        public Nullable<int> BusinessTypeId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual tblBusinessType tblBusinessType { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
        public virtual tblUser tblUser2 { get; set; }
        public virtual tblUser tblUser3 { get; set; }
        public virtual tblUser tblUser4 { get; set; }
        public virtual tblUser tblUser5 { get; set; }
        public virtual tblUser tblUser6 { get; set; }
        public virtual tblUser tblUser7 { get; set; }
    }
}
