//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCEL.DocUpload.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBlowHornTicket
    {
        public int Id { get; set; }
        public string awb_number { get; set; }
        public string delivery_hub { get; set; }
        public string pickup_hub { get; set; }
        public string is_hyperlocal { get; set; }
        public string customer_name { get; set; }
        public string customer_mobile { get; set; }
        public string pin_number { get; set; }
        public string alternate_customer_mobile { get; set; }
        public string customer_email { get; set; }
        public string delivery_address { get; set; }
        public string delivery_postal_code { get; set; }
        public string reference_number { get; set; }
        public string what3words { get; set; }
        public string customer_reference_number { get; set; }
        public string delivery_lat { get; set; }
        public string delivery_lon { get; set; }
        public string pickup_address { get; set; }
        public string pickup_postal_code { get; set; }
        public string pickup_lat { get; set; }
        public string pickup_lon { get; set; }
        public string pickup_customer_name { get; set; }
        public string pickup_customer_mobile { get; set; }
        public string is_return_order { get; set; }
        public string commercial_class { get; set; }
        public string is_commercial_address { get; set; }
        public Nullable<System.DateTime> pickup_datetime { get; set; }
        public string division { get; set; }
        public Nullable<System.DateTime> expected_delivery_time { get; set; }
        public Nullable<bool> is_cod { get; set; }
        public string cash_on_delivery { get; set; }
        public string ProductStatus { get; set; }
        public string SponsrorOrderNo { get; set; }
    }
}
