//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCEL.DocUpload.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBookingItem
    {
        public int BookingItemId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<bool> QCCheck { get; set; }
        public Nullable<bool> QCVerifiedQunatity { get; set; }
        public Nullable<decimal> BookingPrice { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<bool> IsBookingPaymentConfirm { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual tblUser tblUser { get; set; }
        public virtual tblBusinessCustomer tblBusinessCustomer { get; set; }
        public virtual tblItem tblItem { get; set; }
        public virtual tblUser tblUser1 { get; set; }
    }
}
