//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCEL.DocUpload.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCatBrandSweetener
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCatBrandSweetener()
        {
            this.tblCatBrandSweetenerMappings = new HashSet<tblCatBrandSweetenerMapping>();
            this.tblCatBrandSweetenerMappings1 = new HashSet<tblCatBrandSweetenerMapping>();
        }
    
        public int CatBrandSweetenerId { get; set; }
        public string ModelName { get; set; }
        public string Description { get; set; }
        public string Code { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<int> ProductCategoryId { get; set; }
        public Nullable<int> ProductTypeId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<decimal> SweetnerForDTD { get; set; }
        public Nullable<decimal> SweetnerForDTC { get; set; }
        public Nullable<bool> IsDefaultProduct { get; set; }
        public Nullable<int> BusinessUnitId { get; set; }
        public Nullable<decimal> SweetenerBU { get; set; }
        public Nullable<decimal> SweetenerBP { get; set; }
        public Nullable<decimal> SweetenerOwn { get; set; }
        public Nullable<int> BusinessPartnerId { get; set; }
        public Nullable<bool> IsExchange { get; set; }
    
        public virtual tblBrand tblBrand { get; set; }
        public virtual tblBusinessPartner tblBusinessPartner { get; set; }
        public virtual tblBusinessUnit tblBusinessUnit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCatBrandSweetenerMapping> tblCatBrandSweetenerMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCatBrandSweetenerMapping> tblCatBrandSweetenerMappings1 { get; set; }
        public virtual tblProductCategory tblProductCategory { get; set; }
        public virtual tblProductType tblProductType { get; set; }
    }
}
