//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCEL.DocUpload.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCreditRequest
    {
        public int CreditRequestId { get; set; }
        public Nullable<int> WalletTransactionId { get; set; }
        public Nullable<bool> IsCreditRequest { get; set; }
        public Nullable<bool> IsCreditRequestApproved { get; set; }
        public Nullable<int> CreditRequestUserId { get; set; }
        public Nullable<int> CreditRequestApproveUserId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
        public virtual tblUser tblUser2 { get; set; }
        public virtual tblUser tblUser3 { get; set; }
        public virtual tblWalletTransaction tblWalletTransaction { get; set; }
    }
}
