//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCEL.DocUpload.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCoupon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCoupon()
        {
            this.tblExchangeOrders = new HashSet<tblExchangeOrder>();
        }
    
        public int CouponId { get; set; }
        public Nullable<int> CouponMasterId { get; set; }
        public string CouponL1 { get; set; }
        public string CouponL2 { get; set; }
        public string CouponL3 { get; set; }
        public string UsedCoupon { get; set; }
        public Nullable<decimal> UsedCouponValue { get; set; }
        public Nullable<bool> IsUsed { get; set; }
        public Nullable<int> OrderTransId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
        public virtual tblOrderTran tblOrderTran { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblExchangeOrder> tblExchangeOrders { get; set; }
        public virtual tblCouponMaster tblCouponMaster { get; set; }
    }
}
