//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCEL.DocUpload.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCouponMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCouponMaster()
        {
            this.tblCoupons = new HashSet<tblCoupon>();
        }
    
        public int CouponMasterId { get; set; }
        public Nullable<int> BusinessUnitId { get; set; }
        public Nullable<int> BusinessPartnerId { get; set; }
        public string Title { get; set; }
        public Nullable<decimal> TotalValueOfCoupons { get; set; }
        public Nullable<int> CouponCount { get; set; }
        public Nullable<decimal> CouponL1Value { get; set; }
        public Nullable<decimal> CouponL2Value { get; set; }
        public Nullable<decimal> CouponL3Value { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual tblBusinessPartner tblBusinessPartner { get; set; }
        public virtual tblBusinessUnit tblBusinessUnit { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCoupon> tblCoupons { get; set; }
    }
}
