//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCEL.DocUpload.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEvcPartner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEvcPartner()
        {
            this.tblEvcPartnerPreferences = new HashSet<tblEvcPartnerPreference>();
            this.TblEVCWalletHistories = new HashSet<TblEVCWalletHistory>();
            this.tblOrderLGCs = new HashSet<tblOrderLGC>();
            this.TblVehicleJourneyTrackingDetails = new HashSet<TblVehicleJourneyTrackingDetail>();
            this.tblWalletTransactions = new HashSet<tblWalletTransaction>();
            this.tblEVCPODDetails = new HashSet<tblEVCPODDetail>();
        }
    
        public int EvcPartnerId { get; set; }
        public int EVCRegistrationId { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string PinCode { get; set; }
        public int CityId { get; set; }
        public int StateId { get; set; }
        public string ContactNumber { get; set; }
        public string EvcStoreCode { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> Createdby { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ListOfPincode { get; set; }
        public Nullable<bool> IsApprove { get; set; }
        public string EmailId { get; set; }
        public Nullable<int> OldEVCRegistrationId { get; set; }
    
        public virtual tblCity tblCity { get; set; }
        public virtual tblUser tblUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEvcPartnerPreference> tblEvcPartnerPreferences { get; set; }
        public virtual tblEVCRegistration tblEVCRegistration { get; set; }
        public virtual tblUser tblUser1 { get; set; }
        public virtual tblState tblState { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblEVCWalletHistory> TblEVCWalletHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrderLGC> tblOrderLGCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblVehicleJourneyTrackingDetail> TblVehicleJourneyTrackingDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblWalletTransaction> tblWalletTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEVCPODDetail> tblEVCPODDetails { get; set; }
    }
}
