//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCEL.DocUpload.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEVCDispute
    {
        public int EVCDisputeId { get; set; }
        public Nullable<int> EVCRegistrationId { get; set; }
        public Nullable<int> ExchangeOrderId { get; set; }
        public Nullable<int> ProductTypeId { get; set; }
        public Nullable<int> ProductCatId { get; set; }
        public string Status { get; set; }
        public string LevelStatus { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string EVCDisputedescription { get; set; }
        public string Digi2LResponse { get; set; }
        public string Image1 { get; set; }
        public string Image2 { get; set; }
        public string Image3 { get; set; }
        public string Image4 { get; set; }
        public Nullable<int> OrderTransId { get; set; }
        public string DisputeRegno { get; set; }
    
        public virtual tblOrderTran tblOrderTran { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblEVCRegistration tblEVCRegistration { get; set; }
        public virtual tblExchangeOrder tblExchangeOrder { get; set; }
        public virtual tblUser tblUser1 { get; set; }
    }
}
