//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCEL.DocUpload.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEvcPriceMaster
    {
        public int EVCPriceMasterId { get; set; }
        public string SponsorName { get; set; }
        public string ProductGroup { get; set; }
        public Nullable<int> BusinessUnitId { get; set; }
        public Nullable<int> ProductCategoryId { get; set; }
        public string ProductType { get; set; }
        public Nullable<int> ProductTypeId { get; set; }
        public string Size { get; set; }
        public Nullable<int> EVC_P { get; set; }
        public Nullable<int> EVC_Q { get; set; }
        public Nullable<int> EVC_R { get; set; }
        public Nullable<int> EVC_S { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public Nullable<int> LGCCost { get; set; }
    }
}
