//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCEL.DocUpload.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEVCWalletHistory
    {
        public int WalletHistoryId { get; set; }
        public int EVCRegistrationId { get; set; }
        public Nullable<int> OrderTransId { get; set; }
        public Nullable<decimal> CurrentWalletAmount { get; set; }
        public Nullable<decimal> AddAmount { get; set; }
        public Nullable<bool> AmountAdditionFlag { get; set; }
        public Nullable<decimal> FinalOrderAmount { get; set; }
        public Nullable<bool> AmountdeductionFlag { get; set; }
        public Nullable<decimal> BalanceWalletAmount { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string TransactionId { get; set; }
        public Nullable<int> EVCPartnerId { get; set; }
    
        public virtual tblEvcPartner tblEvcPartner { get; set; }
        public virtual tblEVCRegistration tblEVCRegistration { get; set; }
        public virtual tblOrderTran tblOrderTran { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
    }
}
