//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCEL.DocUpload.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblExchangeABBStatusHistory
    {
        public int StatusHistoryId { get; set; }
        public int OrderType { get; set; }
        public string SponsorOrderNumber { get; set; }
        public string RegdNo { get; set; }
        public string ZohoSponsorId { get; set; }
        public Nullable<int> CustId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> OrderTransId { get; set; }
        public string JsonObjectString { get; set; }
        public string Comment { get; set; }
        public Nullable<int> EVCId { get; set; }
        public Nullable<int> ServicepartnerId { get; set; }
        public Nullable<int> DriverDetailId { get; set; }
    
        public virtual tblDriverDetail tblDriverDetail { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblOrderTran tblOrderTran { get; set; }
        public virtual tblServicePartner tblServicePartner { get; set; }
        public virtual tblExchangeOrderStatu tblExchangeOrderStatu { get; set; }
        public virtual tblUser tblUser1 { get; set; }
    }
}
