//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCEL.DocUpload.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEVCRegistration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEVCRegistration()
        {
            this.tblEVCDisputes = new HashSet<tblEVCDispute>();
            this.tblEvcPartners = new HashSet<tblEvcPartner>();
            this.tblEVCPODDetails = new HashSet<tblEVCPODDetail>();
            this.tblOrderLGCs = new HashSet<tblOrderLGC>();
            this.TblEVCWalletHistories = new HashSet<TblEVCWalletHistory>();
            this.TblVehicleJourneyTrackingDetails = new HashSet<TblVehicleJourneyTrackingDetail>();
            this.tblWalletTransactions = new HashSet<tblWalletTransaction>();
        }
    
        public int EVCRegistrationId { get; set; }
        public string ZohoEVCApprovedId { get; set; }
        public string BussinessName { get; set; }
        public Nullable<int> EntityTypeId { get; set; }
        public string EVCRegdNo { get; set; }
        public string ContactPerson { get; set; }
        public string EVCMobileNumber { get; set; }
        public string AlternateMobileNumber { get; set; }
        public string EmailID { get; set; }
        public string RegdAddressLine1 { get; set; }
        public string RegdAddressLine2 { get; set; }
        public string PinCode { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<decimal> EVCWalletAmount { get; set; }
        public string ContactPersonAddress { get; set; }
        public string UploadGSTRegistration { get; set; }
        public string BankName { get; set; }
        public string IFSCCODE { get; set; }
        public string BankAccountNo { get; set; }
        public Nullable<int> InsertOTP { get; set; }
        public Nullable<int> EVCApprovalStatusId { get; set; }
        public Nullable<bool> ISEVCApprovrd { get; set; }
        public string CopyofCancelledCheque { get; set; }
        public string EWasteRegistrationNumber { get; set; }
        public string EWasteCertificate { get; set; }
        public Nullable<bool> IConfirmTermsCondition { get; set; }
        public string POCName { get; set; }
        public string POCPlace { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string GSTNo { get; set; }
        public Nullable<int> UserId { get; set; }
        public string AadharfrontImage { get; set; }
        public string AadharBackImage { get; set; }
        public string ProfilePic { get; set; }
        public string EVCZohoBookName { get; set; }
        public Nullable<bool> IsInHouse { get; set; }
        public string NatureOfBusiness { get; set; }
        public string Country { get; set; }
        public string panNo { get; set; }
        public string accountHolder { get; set; }
        public string branch { get; set; }
        public string utcEmployeeName { get; set; }
        public string utcEmployeeEmail { get; set; }
        public string utcEmployeeContact { get; set; }
        public string approverName { get; set; }
        public string unitDepartment { get; set; }
        public string managerEmail { get; set; }
        public string managerContact { get; set; }
        public string companyRegNo { get; set; }
        public Nullable<bool> IsSweetenerAmtInclude { get; set; }
        public Nullable<int> GSTTypeId { get; set; }
    
        public virtual tblCity tblCity { get; set; }
        public virtual tblEntityType tblEntityType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEVCDispute> tblEVCDisputes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEvcPartner> tblEvcPartners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEVCPODDetail> tblEVCPODDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrderLGC> tblOrderLGCs { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblLoV tblLoV { get; set; }
        public virtual tblUser tblUser1 { get; set; }
        public virtual tblState tblState { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblEVCWalletHistory> TblEVCWalletHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblVehicleJourneyTrackingDetail> TblVehicleJourneyTrackingDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblWalletTransaction> tblWalletTransactions { get; set; }
    }
}
