//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCEL.DocUpload.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEcomPhoneSpecific
    {
        public int EcomPhoneSpecificId { get; set; }
        public string VoucherCode { get; set; }
        public string Phoneno { get; set; }
        public Nullable<int> EcomVoucherId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Voucherstatus { get; set; }
        public Nullable<bool> IsUsed { get; set; }
    
        public virtual tblUser tblUser { get; set; }
        public virtual tblEcomVoucher tblEcomVoucher { get; set; }
        public virtual tblUser tblUser1 { get; set; }
    }
}
