//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCEL.DocUpload.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEVCApproved
    {
        public int Id { get; set; }
        public string ZohoEVCApprovedId { get; set; }
        public string BussinessName { get; set; }
        public string EVCRegdNo { get; set; }
        public string ContactPerson { get; set; }
        public string EVCMobileNumber { get; set; }
        public string EmailID { get; set; }
        public string RegdAddressLine1 { get; set; }
        public string RegdAddressLine2 { get; set; }
        public string PinCode { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string EVCWalletAmount { get; set; }
        public string ContactPersonAddress { get; set; }
        public string UploadGSTRegistration { get; set; }
        public string CopyofCancelledCheque { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
