//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCEL.DocUpload.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEVCWalletStatu
    {
        public int WalletStatusId { get; set; }
        public Nullable<int> EVCRegistrationId { get; set; }
        public string RegdNo { get; set; }
        public Nullable<int> OrderTransId { get; set; }
        public Nullable<int> WalletTransStatusId { get; set; }
    }
}
