//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCEL.DocUpload.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFeedBack
    {
        public int Id { get; set; }
        public string RatingNo { get; set; }
        public Nullable<int> QuestionId { get; set; }
        public Nullable<int> AnswerId { get; set; }
        public string Comment { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> ExchangeOrderId { get; set; }
    
        public virtual tblCustomerDetail tblCustomerDetail { get; set; }
        public virtual tblExchangeOrder tblExchangeOrder { get; set; }
        public virtual tblFeedBackAnswer tblFeedBackAnswer { get; set; }
        public virtual tblFeedBackQuestion tblFeedBackQuestion { get; set; }
    }
}
