//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCEL.DocUpload.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLogin_Mobile
    {
        public int id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string UserRoleName { get; set; }
        public string UserDeviceId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string DeviceType { get; set; }
        public string MobileNumber { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> UserLoginTypeId { get; set; }
    
        public virtual tblUser tblUser { get; set; }
    }
}
