//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCEL.DocUpload.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLogistic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblLogistic()
        {
            this.tblOrderLGCs = new HashSet<tblOrderLGC>();
        }
    
        public int LogisticId { get; set; }
        public string RegdNo { get; set; }
        public string TicketNumber { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> Modifiedby { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ServicePartnerId { get; set; }
        public Nullable<int> OrderTransId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<decimal> AmtPaybleThroughLGC { get; set; }
        public Nullable<int> driverDetailsId { get; set; }
        public Nullable<bool> isOrderAcceptedByDriver { get; set; }
        public Nullable<bool> isOrderRejectedByDriver { get; set; }
        public string RescheduleComment { get; set; }
        public Nullable<System.DateTime> Rescheduledate { get; set; }
        public Nullable<int> RescheduleCount { get; set; }
        public Nullable<System.DateTime> PickupScheduleDate { get; set; }
    
        public virtual tblExchangeOrderStatu tblExchangeOrderStatu { get; set; }
        public virtual tblOrderTran tblOrderTran { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrderLGC> tblOrderLGCs { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
        public virtual tblServicePartner tblServicePartner { get; set; }
        public virtual tblDriverDetail tblDriverDetail { get; set; }
    }
}
