//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCEL.DocUpload.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMahindraLogistic
    {
        public int Id { get; set; }
        public string client_order_id { get; set; }
        public string deliveryAddress { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string zipcode { get; set; }
        public string street_address { get; set; }
        public string telephone { get; set; }
        public string state { get; set; }
        public string city { get; set; }
        public string email { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public string pickUpAddress { get; set; }
        public string first_name_pickup { get; set; }
        public string last_name_pickup { get; set; }
        public string zipcode_pickup { get; set; }
        public string street_address_pickup { get; set; }
        public string telephone_pickup { get; set; }
        public string state_pickup { get; set; }
        public string city_pickup { get; set; }
        public string email_pickup { get; set; }
        public string latitude_pickup { get; set; }
        public string longitude_pickup { get; set; }
        public string sku { get; set; }
        public string name { get; set; }
        public string price_per_each_item { get; set; }
        public Nullable<decimal> total_price { get; set; }
        public Nullable<int> quantity { get; set; }
        public string first_name_none { get; set; }
        public string last_name_none { get; set; }
        public string telephone_none { get; set; }
        public string email_none { get; set; }
        public string orderId { get; set; }
        public string awbNumber { get; set; }
        public string wmsOrderId { get; set; }
        public string order_delivery_date { get; set; }
    }
}
