//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCEL.DocUpload.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrderTran
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblOrderTran()
        {
            this.tblCoupons = new HashSet<tblCoupon>();
            this.tblCustomerDetails = new HashSet<tblCustomerDetail>();
            this.tblCustomerFiles = new HashSet<tblCustomerFile>();
            this.tblEVCDisputes = new HashSet<tblEVCDispute>();
            this.tblEVCPODDetails = new HashSet<tblEVCPODDetail>();
            this.TblEVCWalletHistories = new HashSet<TblEVCWalletHistory>();
            this.tblExchangeABBStatusHistories = new HashSet<tblExchangeABBStatusHistory>();
            this.tblLogistics = new HashSet<tblLogistic>();
            this.tblOrderLGCs = new HashSet<tblOrderLGC>();
            this.tblOrderQCs = new HashSet<tblOrderQC>();
            this.tblOrderQCRatings = new HashSet<tblOrderQCRating>();
            this.tblWalletTransactions = new HashSet<tblWalletTransaction>();
            this.tblTempDatas = new HashSet<tblTempData>();
            this.TblVehicleJourneyTrackingDetails = new HashSet<TblVehicleJourneyTrackingDetail>();
        }
    
        public int OrderTransId { get; set; }
        public Nullable<int> OrderType { get; set; }
        public Nullable<int> ExchangeId { get; set; }
        public Nullable<int> ABBRedemptionId { get; set; }
        public string SponsorOrderNumber { get; set; }
        public string RegdNo { get; set; }
        public Nullable<decimal> ExchangePrice { get; set; }
        public Nullable<decimal> QuotedPrice { get; set; }
        public Nullable<decimal> Sweetner { get; set; }
        public Nullable<decimal> FinalPriceAfterQC { get; set; }
        public Nullable<int> EVCPriceMasterId { get; set; }
        public Nullable<decimal> EVCPrice { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<bool> AmountPaidToCustomer { get; set; }
        public Nullable<int> SelfQCLinkResendby { get; set; }
        public Nullable<int> AssignBy { get; set; }
        public Nullable<int> AssignTo { get; set; }
        public Nullable<decimal> UnInstallationPrice { get; set; }
        public Nullable<bool> IsUnInstallationPricePaid { get; set; }
        public string PDVerificatonCode { get; set; }
    
        public virtual tblABBRedemption tblABBRedemption { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCoupon> tblCoupons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCustomerDetail> tblCustomerDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCustomerFile> tblCustomerFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEVCDispute> tblEVCDisputes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEVCPODDetail> tblEVCPODDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblEVCWalletHistory> TblEVCWalletHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblExchangeABBStatusHistory> tblExchangeABBStatusHistories { get; set; }
        public virtual tblExchangeOrder tblExchangeOrder { get; set; }
        public virtual tblExchangeOrderStatu tblExchangeOrderStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLogistic> tblLogistics { get; set; }
        public virtual tblLoV tblLoV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrderLGC> tblOrderLGCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrderQC> tblOrderQCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrderQCRating> tblOrderQCRatings { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
        public virtual tblUser tblUser2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblWalletTransaction> tblWalletTransactions { get; set; }
        public virtual tblUser tblUser3 { get; set; }
        public virtual tblUser tblUser4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTempData> tblTempDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblVehicleJourneyTrackingDetail> TblVehicleJourneyTrackingDetails { get; set; }
    }
}
