//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCEL.DocUpload.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrderLGC
    {
        public int OrderLGCId { get; set; }
        public int OrderTransId { get; set; }
        public Nullable<System.DateTime> ProposedPickDate { get; set; }
        public string LGCComments { get; set; }
        public Nullable<decimal> LGCPayableAmt { get; set; }
        public Nullable<System.DateTime> ActualPickupDate { get; set; }
        public Nullable<System.DateTime> ActualDropDate { get; set; }
        public string SecondaryOrderFlag { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> EVCPODId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> LogisticId { get; set; }
        public string custDeclartionpdfname { get; set; }
        public Nullable<int> DriverDetailsId { get; set; }
        public Nullable<int> EVCRegistrationId { get; set; }
        public Nullable<bool> IsInvoiceGenerated { get; set; }
        public Nullable<int> EVCPartnerId { get; set; }
    
        public virtual tblDriverDetail tblDriverDetail { get; set; }
        public virtual tblEvcPartner tblEvcPartner { get; set; }
        public virtual tblEVCPODDetail tblEVCPODDetail { get; set; }
        public virtual tblEVCRegistration tblEVCRegistration { get; set; }
        public virtual tblLogistic tblLogistic { get; set; }
        public virtual tblOrderTran tblOrderTran { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
    }
}
