//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCEL.DocUpload.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrderQC
    {
        public int OrderQCId { get; set; }
        public Nullable<int> OrderTransId { get; set; }
        public Nullable<System.DateTime> ProposedQCDate { get; set; }
        public string QCComments { get; set; }
        public string QualityAfterQC { get; set; }
        public Nullable<decimal> PriceAfterQC { get; set; }
        public Nullable<System.DateTime> QCDate { get; set; }
        public Nullable<int> BonusType { get; set; }
        public Nullable<decimal> BonusbyQC { get; set; }
        public Nullable<decimal> AdditionalBonus { get; set; }
        public Nullable<int> PromotionalVoucherId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string FrontViewImage { get; set; }
        public string SideViewImage { get; set; }
        public string SrNumberImage { get; set; }
        public string InsideViewImage { get; set; }
        public string PaymentImage { get; set; }
        public string ShortVideoName { get; set; }
        public Nullable<bool> IsPaymentConnected { get; set; }
        public Nullable<decimal> CollectedAmount { get; set; }
        public Nullable<int> Reschedulecount { get; set; }
        public Nullable<bool> IsUPIno { get; set; }
        public string RescheduleNote { get; set; }
        public Nullable<System.DateTime> PreferredPickupDate { get; set; }
        public string UPIId { get; set; }
        public Nullable<decimal> AverageSellingPrice { get; set; }
        public Nullable<decimal> ExcellentPriceByASP { get; set; }
        public Nullable<decimal> QuotedPrice { get; set; }
        public Nullable<decimal> Sweetner { get; set; }
        public Nullable<decimal> QuotedWithSweetner { get; set; }
        public Nullable<decimal> BonusPercentQC { get; set; }
        public Nullable<decimal> BonusPercentAdmin { get; set; }
        public Nullable<decimal> FinalCalculatedWeightage { get; set; }
        public string PickupStartTime { get; set; }
        public string PickupEndTime { get; set; }
        public string DagnosticPdfName { get; set; }
        public Nullable<bool> IsInvoiceValidated { get; set; }
        public Nullable<bool> IsInstallationValidated { get; set; }
        public Nullable<decimal> SweetenerBU { get; set; }
        public Nullable<decimal> SweetenerBP { get; set; }
        public Nullable<decimal> SweetenerDigi2l { get; set; }
        public Nullable<decimal> Sweetener { get; set; }
    
        public virtual tblUser tblUser { get; set; }
        public virtual tblOrderTran tblOrderTran { get; set; }
    }
}
