//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCEL.DocUpload.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrderBasedConfig
    {
        public int Id { get; set; }
        public int BusinessUnitId { get; set; }
        public Nullable<int> BusinessPartnerId { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<bool> IsBPMultiBrand { get; set; }
        public Nullable<bool> IsValidationBasedSweetener { get; set; }
        public Nullable<bool> IsSweetenerModalBased { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual tblBrand tblBrand { get; set; }
        public virtual tblBusinessPartner tblBusinessPartner { get; set; }
        public virtual tblBusinessUnit tblBusinessUnit { get; set; }
    }
}
