//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCEL.DocUpload.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrderQCRating
    {
        public int OrderQCRatingId { get; set; }
        public int OrderTransId { get; set; }
        public Nullable<int> ProductCatId { get; set; }
        public Nullable<int> QCQuestionId { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<decimal> CalculatedWeightage { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string QcComments { get; set; }
        public Nullable<int> QuestionerLOVId { get; set; }
        public Nullable<int> DoneBy { get; set; }
    
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
        public virtual tblOrderTran tblOrderTran { get; set; }
        public virtual tblProductCategory tblProductCategory { get; set; }
        public virtual tblQCRatingMaster tblQCRatingMaster { get; set; }
        public virtual TblQuestionerLOV TblQuestionerLOV { get; set; }
    }
}
