//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCEL.DocUpload.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrderPromoVoucher
    {
        public int OrderPromoVoucherId { get; set; }
        public Nullable<int> OrderTransId { get; set; }
        public Nullable<int> CustId { get; set; }
        public string VoucherCode { get; set; }
        public Nullable<int> VoucherAmt { get; set; }
        public Nullable<int> VoucherStatus { get; set; }
        public Nullable<bool> IsVoucherUsed { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
