//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCEL.DocUpload.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProductCategory()
        {
            this.tblABBPlanMasters = new HashSet<tblABBPlanMaster>();
            this.tblABBPriceMasters = new HashSet<tblABBPriceMaster>();
            this.tblABBRegistrations = new HashSet<tblABBRegistration>();
            this.TblBrandGroups = new HashSet<TblBrandGroup>();
            this.tblBrandSmartBuys = new HashSet<tblBrandSmartBuy>();
            this.tblBUProductCategoryMappings = new HashSet<tblBUProductCategoryMapping>();
            this.tblBUProductCategoryMappings1 = new HashSet<tblBUProductCategoryMapping>();
            this.tblEvcPartnerPreferences = new HashSet<tblEvcPartnerPreference>();
            this.tblImageLabelMasters = new HashSet<tblImageLabelMaster>();
            this.tblModelNumbers = new HashSet<tblModelNumber>();
            this.tblOrderQCRatings = new HashSet<tblOrderQCRating>();
            this.tblPriceMasters = new HashSet<tblPriceMaster>();
            this.TblPriceMasterQuestioners = new HashSet<TblPriceMasterQuestioner>();
            this.TblProdCatBrandMappings = new HashSet<TblProdCatBrandMapping>();
            this.TblProductTechnologies = new HashSet<TblProductTechnology>();
            this.tblProductTypes = new HashSet<tblProductType>();
            this.tblUniversalPriceMasters = new HashSet<tblUniversalPriceMaster>();
            this.UniversalPriceMasters = new HashSet<UniversalPriceMaster>();
            this.tblProductQualityIndexes = new HashSet<tblProductQualityIndex>();
            this.tblVoucherVerfications = new HashSet<tblVoucherVerfication>();
            this.tblProductConditionLabels = new HashSet<tblProductConditionLabel>();
            this.tblQCRatingMasterMappings = new HashSet<tblQCRatingMasterMapping>();
            this.TblQuestionerLOVMappings = new HashSet<TblQuestionerLOVMapping>();
            this.tblSponsorCategoryMappings = new HashSet<tblSponsorCategoryMapping>();
            this.tblUninstallationPrices = new HashSet<tblUninstallationPrice>();
            this.TblVehicleIncentives = new HashSet<TblVehicleIncentive>();
            this.tblCatBrandSweeteners = new HashSet<tblCatBrandSweetener>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Code { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Description_For_ABB { get; set; }
        public Nullable<bool> IsAllowedForOld { get; set; }
        public Nullable<bool> IsAllowedForNew { get; set; }
        public string CommentForWorking { get; set; }
        public string ProductCategoryImage { get; set; }
        public Nullable<decimal> ASPPercentage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblABBPlanMaster> tblABBPlanMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblABBPriceMaster> tblABBPriceMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblABBRegistration> tblABBRegistrations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblBrandGroup> TblBrandGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBrandSmartBuy> tblBrandSmartBuys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBUProductCategoryMapping> tblBUProductCategoryMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBUProductCategoryMapping> tblBUProductCategoryMappings1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEvcPartnerPreference> tblEvcPartnerPreferences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblImageLabelMaster> tblImageLabelMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblModelNumber> tblModelNumbers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrderQCRating> tblOrderQCRatings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPriceMaster> tblPriceMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblPriceMasterQuestioner> TblPriceMasterQuestioners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblProdCatBrandMapping> TblProdCatBrandMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblProductTechnology> TblProductTechnologies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProductType> tblProductTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUniversalPriceMaster> tblUniversalPriceMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UniversalPriceMaster> UniversalPriceMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProductQualityIndex> tblProductQualityIndexes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblVoucherVerfication> tblVoucherVerfications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProductConditionLabel> tblProductConditionLabels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblQCRatingMasterMapping> tblQCRatingMasterMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblQuestionerLOVMapping> TblQuestionerLOVMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSponsorCategoryMapping> tblSponsorCategoryMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUninstallationPrice> tblUninstallationPrices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblVehicleIncentive> TblVehicleIncentives { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCatBrandSweetener> tblCatBrandSweeteners { get; set; }
    }
}
