//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCEL.DocUpload.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProductType()
        {
            this.tblABBPlanMasters = new HashSet<tblABBPlanMaster>();
            this.tblExchangeOrders = new HashSet<tblExchangeOrder>();
            this.tblModelNumbers = new HashSet<tblModelNumber>();
            this.tblPriceMasters = new HashSet<tblPriceMaster>();
            this.tblVoucherVerfications = new HashSet<tblVoucherVerfication>();
            this.tblABBRegistrations = new HashSet<tblABBRegistration>();
            this.tblImageLabelMasters = new HashSet<tblImageLabelMaster>();
            this.tblABBPriceMasters = new HashSet<tblABBPriceMaster>();
            this.tblExchangeOrders1 = new HashSet<tblExchangeOrder>();
            this.tblBUProductCategoryMappings = new HashSet<tblBUProductCategoryMapping>();
            this.tblUniversalPriceMasters = new HashSet<tblUniversalPriceMaster>();
            this.tblUninstallationPrices = new HashSet<tblUninstallationPrice>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Code { get; set; }
        public string Size { get; set; }
        public Nullable<int> ProductCatId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Description_For_ABB { get; set; }
        public Nullable<bool> IsAllowedForOld { get; set; }
        public Nullable<bool> IsAllowedForNew { get; set; }
        public string ProductTypeImage { get; set; }
        public Nullable<bool> IsusedNew { get; set; }
        public Nullable<bool> Isusedold { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblABBPlanMaster> tblABBPlanMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblExchangeOrder> tblExchangeOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblModelNumber> tblModelNumbers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPriceMaster> tblPriceMasters { get; set; }
        public virtual tblProductCategory tblProductCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblVoucherVerfication> tblVoucherVerfications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblABBRegistration> tblABBRegistrations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblImageLabelMaster> tblImageLabelMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblABBPriceMaster> tblABBPriceMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblExchangeOrder> tblExchangeOrders1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBUProductCategoryMapping> tblBUProductCategoryMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUniversalPriceMaster> tblUniversalPriceMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUninstallationPrice> tblUninstallationPrices { get; set; }
    }
}
