//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCEL.DocUpload.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductConditionLabel
    {
        public int Id { get; set; }
        public string PCLabelName { get; set; }
        public Nullable<int> OrderSequence { get; set; }
        public int BusinessUnitId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> Modifieddate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> BusinessPartnerId { get; set; }
        public Nullable<bool> IsSweetenerApplicable { get; set; }
        public Nullable<int> ProductCatId { get; set; }
        public Nullable<bool> IsOldProductBaseSweetener { get; set; }
    
        public virtual tblBusinessPartner tblBusinessPartner { get; set; }
        public virtual tblBusinessUnit tblBusinessUnit { get; set; }
        public virtual tblProductCategory tblProductCategory { get; set; }
    }
}
