//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCEL.DocUpload.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPriceMaster
    {
        public int Id { get; set; }
        public string ZohoPriceMasterId { get; set; }
        public string ExchPriceCode { get; set; }
        public Nullable<int> ProductCategoryId { get; set; }
        public string ProductCat { get; set; }
        public Nullable<int> ProductTypeId { get; set; }
        public string ProductType { get; set; }
        public string ProductTypeCode { get; set; }
        public string BrandName_1 { get; set; }
        public string BrandName_2 { get; set; }
        public string BrandName_3 { get; set; }
        public string BrandName_4 { get; set; }
        public string Quote_P_High { get; set; }
        public string Quote_Q_High { get; set; }
        public string Quote_R_High { get; set; }
        public string Quote_S_High { get; set; }
        public string Quote_P { get; set; }
        public string Quote_Q { get; set; }
        public string Quote_R { get; set; }
        public string Quote_S { get; set; }
        public string PriceStartDate { get; set; }
        public string PriceEndDate { get; set; }
        public string OtherBrand { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual tblProductCategory tblProductCategory { get; set; }
        public virtual tblProductType tblProductType { get; set; }
    }
}
