//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCEL.DocUpload.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPaymentLeaser
    {
        public int Id { get; set; }
        public string RegdNo { get; set; }
        public string transactionId { get; set; }
        public string OrderId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> PaymentStatus { get; set; }
        public string paymentResponse { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string Bank { get; set; }
        public string BankId { get; set; }
        public string CardId { get; set; }
        public string CardScheme { get; set; }
        public string CardToken { get; set; }
        public string CardHashId { get; set; }
        public string CheckSum { get; set; }
        public string PaymentMode { get; set; }
        public string ResponseCode { get; set; }
        public string ResponseDescription { get; set; }
        public string TransactionType { get; set; }
        public string ModuleType { get; set; }
        public Nullable<int> ModuleReferenceId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string GatewayTransactioId { get; set; }
        public string OrderStatus { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string UTCReferenceID { get; set; }
    }
}
