//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCEL.DocUpload.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductQualityIndex
    {
        public int ProductQualityIndexId { get; set; }
        public string Name { get; set; }
        public Nullable<int> ProductCategoryId { get; set; }
        public string CategoryName { get; set; }
        public string ExcellentDesc { get; set; }
        public string GoodDesc { get; set; }
        public string AverageDesc { get; set; }
        public string NonWorkingDesc { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual tblProductCategory tblProductCategory { get; set; }
    }
}
