//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCEL.DocUpload.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPriceMasterQuestioner
    {
        public int PriceMasterQuestionerId { get; set; }
        public Nullable<int> ProductTypeId { get; set; }
        public Nullable<int> BusinessUnitId { get; set; }
        public Nullable<int> ProductTechnologyId { get; set; }
        public Nullable<decimal> AverageSellingPrice { get; set; }
        public Nullable<decimal> NonWorkingPrice { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ProductCatId { get; set; }
        public Nullable<bool> IsDiagnoseV2 { get; set; }
    
        public virtual tblBusinessUnit tblBusinessUnit { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
        public virtual tblProductType tblProductType { get; set; }
        public virtual TblProductTechnology TblProductTechnology { get; set; }
        public virtual tblProductCategory tblProductCategory { get; set; }
    }
}
