//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCEL.DocUpload.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQCRatingMasterMapping
    {
        public int QCRatingMasterMappingId { get; set; }
        public Nullable<int> QCRatingId { get; set; }
        public Nullable<int> ProductCatId { get; set; }
        public Nullable<int> ProductTypeId { get; set; }
        public Nullable<int> ProductTechnologyId { get; set; }
        public Nullable<int> QuestsSequence { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual tblProductCategory tblProductCategory { get; set; }
        public virtual TblProductTechnology TblProductTechnology { get; set; }
        public virtual tblProductType tblProductType { get; set; }
        public virtual tblQCRatingMaster tblQCRatingMaster { get; set; }
    }
}
