//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCEL.DocUpload.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRoleAccess
    {
        public int RoleAccessId { get; set; }
        public Nullable<int> AccessListId { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> CanAdd { get; set; }
        public Nullable<bool> CanView { get; set; }
        public Nullable<bool> CanDelete { get; set; }
        public Nullable<int> CompanyId { get; set; }
    
        public virtual tblAccessList tblAccessList { get; set; }
        public virtual tblCompany tblCompany { get; set; }
        public virtual tblRole tblRole { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
    }
}
