//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCEL.DocUpload.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRefurbisherRegistration
    {
        public int RefurbisherId { get; set; }
        public string RefurbisherName { get; set; }
        public Nullable<int> EntityTypeId { get; set; }
        public string TypeofServices { get; set; }
        public string NatureOfBusiness { get; set; }
        public string ContactPerson { get; set; }
        public string Address { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> StateId { get; set; }
        public string Country { get; set; }
        public string PostalCode { get; set; }
        public string Telephone { get; set; }
        public string Mobile { get; set; }
        public string GSTDeclaration { get; set; }
        public string GSTNo { get; set; }
        public string PanNo { get; set; }
        public string EmailId { get; set; }
        public string CompanyRegNo { get; set; }
        public string AccountHolder { get; set; }
        public string BankName { get; set; }
        public string Branch { get; set; }
        public string BankAccountNo { get; set; }
        public string IFSCCode { get; set; }
        public string UTCEmployeeName { get; set; }
        public string UTCEmployeeEmail { get; set; }
        public string UTCEmployeeContact { get; set; }
        public string RefurbisherApprovalName { get; set; }
        public string UnitDepartment { get; set; }
        public string ManagerEmail { get; set; }
        public string ManagerContact { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual tblCity tblCity { get; set; }
        public virtual tblEntityType tblEntityType { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
        public virtual tblState tblState { get; set; }
    }
}
