//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCEL.DocUpload.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSelfQC
    {
        public int SelfQCId { get; set; }
        public string ImageName { get; set; }
        public string RegdNo { get; set; }
        public Nullable<bool> IsExchange { get; set; }
        public Nullable<bool> IsABB { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Modifiedby { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ExchangeOrderId { get; set; }
        public Nullable<int> RedemptionId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual tblExchangeOrder tblExchangeOrder { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblABBRedemption tblABBRedemption { get; set; }
    }
}
