//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCEL.DocUpload.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTempData
    {
        public int Id { get; set; }
        public string RegdNo { get; set; }
        public string FileName { get; set; }
        public Nullable<int> LovId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> ImageLabelid { get; set; }
        public Nullable<int> OrderTransId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> Modifiedby { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual tblExchangeOrderStatu tblExchangeOrderStatu { get; set; }
        public virtual tblImageLabelMaster tblImageLabelMaster { get; set; }
        public virtual tblLoV tblLoV { get; set; }
        public virtual tblOrderTran tblOrderTran { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
    }
}
