//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCEL.DocUpload.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVoucherVerfication
    {
        public int VoucherVerficationId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> ExchangeOrderId { get; set; }
        public string InvoiceName { get; set; }
        public Nullable<bool> IsDealerConfirm { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string VoucherCode { get; set; }
        public Nullable<bool> IsVoucherused { get; set; }
        public string InvoiceImageName { get; set; }
        public Nullable<int> BusinessPartnerId { get; set; }
        public Nullable<int> NewProductCategoryId { get; set; }
        public Nullable<int> NewProductTypeId { get; set; }
        public Nullable<int> NewBrandId { get; set; }
        public Nullable<int> ModelNumberId { get; set; }
        public Nullable<decimal> ExchangePrice { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<decimal> Sweetneer { get; set; }
        public Nullable<int> VoucherStatusId { get; set; }
        public Nullable<int> RedemptionId { get; set; }
    
        public virtual tblBrand tblBrand { get; set; }
        public virtual tblBusinessPartner tblBusinessPartner { get; set; }
        public virtual tblCustomerDetail tblCustomerDetail { get; set; }
        public virtual tblExchangeOrder tblExchangeOrder { get; set; }
        public virtual tblModelNumber tblModelNumber { get; set; }
        public virtual tblProductCategory tblProductCategory { get; set; }
        public virtual tblProductType tblProductType { get; set; }
        public virtual tblVoucherStatu tblVoucherStatu { get; set; }
        public virtual tblABBRedemption tblABBRedemption { get; set; }
    }
}
