//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCEL.DocUpload.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblVehicleJourneyTrackingDetail
    {
        public int TrackingDetailsId { get; set; }
        public Nullable<int> TrackingId { get; set; }
        public Nullable<int> ServicePartnerID { get; set; }
        public Nullable<int> DriverId { get; set; }
        public Nullable<int> EVCId { get; set; }
        public Nullable<int> OrderTransId { get; set; }
        public Nullable<System.DateTime> JourneyPlanDate { get; set; }
        public string PickupLatt { get; set; }
        public string PickupLong { get; set; }
        public string DropLatt { get; set; }
        public string DropLong { get; set; }
        public Nullable<System.DateTime> PickupStartDatetime { get; set; }
        public Nullable<System.DateTime> PickupEndDatetime { get; set; }
        public Nullable<System.DateTime> OrderDropTime { get; set; }
        public Nullable<System.TimeSpan> PickupTat { get; set; }
        public Nullable<System.TimeSpan> DropTat { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<decimal> BasePrice { get; set; }
        public Nullable<decimal> PickupInc { get; set; }
        public Nullable<decimal> PackingInc { get; set; }
        public Nullable<decimal> DropInc { get; set; }
        public Nullable<decimal> DropImageInc { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> EstimateEarning { get; set; }
        public Nullable<bool> IsPackedImg { get; set; }
        public Nullable<int> EVCPartnerId { get; set; }
    
        public virtual tblDriverDetail tblDriverDetail { get; set; }
        public virtual tblEvcPartner tblEvcPartner { get; set; }
        public virtual tblEVCRegistration tblEVCRegistration { get; set; }
        public virtual tblExchangeOrderStatu tblExchangeOrderStatu { get; set; }
        public virtual tblOrderTran tblOrderTran { get; set; }
        public virtual tblServicePartner tblServicePartner { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
        public virtual TblVehicleJourneyTracking TblVehicleJourneyTracking { get; set; }
    }
}
