//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCEL.DocUpload.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVehicleList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblVehicleList()
        {
            this.tblDriverDetails = new HashSet<tblDriverDetail>();
            this.tblDriverDetails1 = new HashSet<tblDriverDetail>();
        }
    
        public int VehicleId { get; set; }
        public string VehicleNumber { get; set; }
        public string Vehicle_RC_Number { get; set; }
        public string Vehicle_RC_Certificate { get; set; }
        public string VehiclefitnessCertificate { get; set; }
        public string VehicleInsuranceCertificate { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> ServicePartnerId { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual tblCity tblCity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDriverDetail> tblDriverDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDriverDetail> tblDriverDetails1 { get; set; }
        public virtual tblServicePartner tblServicePartner { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
        public virtual tblVehicleList tblVehicleList1 { get; set; }
        public virtual tblVehicleList tblVehicleList2 { get; set; }
    }
}
