//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCEL.DocUpload.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWhatsAppMessage
    {
        public int Id { get; set; }
        public string PhoneNumber { get; set; }
        public string TemplateName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public string msgId { get; set; }
        public string code { get; set; }
    }
}
