//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCEL.DocUpload.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWalletTransaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblWalletTransaction()
        {
            this.tblCreditRequests = new HashSet<tblCreditRequest>();
        }
    
        public int WalletTransactionId { get; set; }
        public Nullable<int> EVCRegistrationId { get; set; }
        public string RegdNo { get; set; }
        public string SponserOrderNo { get; set; }
        public string StatusId { get; set; }
        public Nullable<decimal> OrderAmount { get; set; }
        public Nullable<System.DateTime> OrderOfDeliverdDate { get; set; }
        public Nullable<System.DateTime> OrderOfCompleteDate { get; set; }
        public Nullable<System.DateTime> OrderOfInprogressDate { get; set; }
        public string OrderType { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ZohoAllocationId { get; set; }
        public Nullable<System.DateTime> OrderofAssignDate { get; set; }
        public Nullable<int> OrderTransId { get; set; }
        public Nullable<bool> IsPrimeProductId { get; set; }
        public Nullable<int> OldEVCId { get; set; }
        public Nullable<int> NewEVCId { get; set; }
        public Nullable<int> ReassignCount { get; set; }
        public Nullable<int> EVCPartnerId { get; set; }
        public Nullable<bool> IsOrderAmtWithSweetener { get; set; }
        public Nullable<int> GSTTypeId { get; set; }
        public Nullable<decimal> BaseValue { get; set; }
        public Nullable<decimal> CGSTAmt { get; set; }
        public Nullable<decimal> SGSTAmt { get; set; }
        public Nullable<decimal> IGSTAmt { get; set; }
        public Nullable<decimal> SweetenerAmt { get; set; }
        public Nullable<int> LGCCost { get; set; }
        public Nullable<decimal> PrimeProductDiffAmt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCreditRequest> tblCreditRequests { get; set; }
        public virtual tblEvcPartner tblEvcPartner { get; set; }
        public virtual tblEVCRegistration tblEVCRegistration { get; set; }
        public virtual tblLoV tblLoV { get; set; }
        public virtual tblOrderTran tblOrderTran { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
    }
}
