//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCEL.DocUpload.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_AllABBRedemptionData
    {
        public string RegdNo { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> ABBRegistrationId { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string Current_Status { get; set; }
        public string StatusName { get; set; }
        public string StatusDescription { get; set; }
        public Nullable<decimal> RedemptionValue { get; set; }
        public Nullable<System.DateTime> RedemptionDate { get; set; }
        public Nullable<int> RedemptionPeriod { get; set; }
        public Nullable<int> RedemptionPercentage { get; set; }
        public int RedemptionId { get; set; }
        public Nullable<System.DateTime> SelfQCDate { get; set; }
        public string QCFlag { get; set; }
        public string ProposedQCDate { get; set; }
        public Nullable<System.DateTime> QCDate { get; set; }
        public string QCComments { get; set; }
        public string upiid { get; set; }
        public string QualityAfterQC { get; set; }
        public Nullable<decimal> PriceAfterQC { get; set; }
        public string PreferredPickupDate { get; set; }
        public string EVC_Allocated { get; set; }
        public Nullable<decimal> EVCPrice { get; set; }
        public Nullable<System.DateTime> EVC_AssignedDate { get; set; }
        public string Logistics_Partner { get; set; }
        public string TicketNumber { get; set; }
        public Nullable<System.DateTime> Ticket_Generation_Date { get; set; }
        public Nullable<System.DateTime> CancellationDate { get; set; }
        public Nullable<System.DateTime> Rescheduledate { get; set; }
        public Nullable<System.DateTime> ProposedPickDate { get; set; }
        public Nullable<System.DateTime> ActualPickupDate { get; set; }
        public Nullable<System.DateTime> ActualDropDate { get; set; }
        public string LGCComments { get; set; }
        public Nullable<decimal> LGCPayableAmt { get; set; }
        public string POD_Name { get; set; }
        public string BusinessPartnerName { get; set; }
        public string BusinessUnit { get; set; }
        public string Product_Cat { get; set; }
        public string ProdCatCode { get; set; }
        public string Product_Type { get; set; }
        public string ProdTypeCode { get; set; }
        public string BrandName { get; set; }
        public string Pincode { get; set; }
        public string City { get; set; }
        public Nullable<System.DateTime> Order_Date { get; set; }
        public string Voucher_No { get; set; }
        public Nullable<System.DateTime> Issue_Date { get; set; }
        public string Cust_Name { get; set; }
        public string Cust_E_mail { get; set; }
        public string Cust_Mobile { get; set; }
        public string Cust_City { get; set; }
        public string Cust_State { get; set; }
        public string Cust_ZipCode { get; set; }
        public string Is_ORC { get; set; }
        public string StoreName { get; set; }
        public string StoreCode { get; set; }
        public Nullable<System.DateTime> InstallationDate { get; set; }
        public string SponsorServiceRefId { get; set; }
    }
}
