//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCEL.DocUpload.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_BOSCHVoucher
    {
        public string RegdNo { get; set; }
        public string Payer_Code { get; set; }
        public string Payer_Phone { get; set; }
        public string Payer_Email { get; set; }
        public string Store_Name { get; set; }
        public string Location { get; set; }
        public string Pincode { get; set; }
        public string City { get; set; }
        public string Is_From_Home { get; set; }
        public Nullable<System.DateTime> Order_Date { get; set; }
        public string Cust_Name { get; set; }
        public string Cust_E_mail { get; set; }
        public string Cust_Mobile { get; set; }
        public string Address_1 { get; set; }
        public string Address_2 { get; set; }
        public string Cust__City { get; set; }
        public string Cust_ZipCode { get; set; }
        public string Old_Prod_Group { get; set; }
        public string Old_Prod_Type { get; set; }
        public string Brandname { get; set; }
        public string Voucher_No { get; set; }
        public Nullable<System.DateTime> Issue_Date { get; set; }
        public string Voucher_Status { get; set; }
        public Nullable<decimal> Voucher_Amt { get; set; }
        public Nullable<decimal> Old_Product_Price { get; set; }
        public Nullable<decimal> Sweetener_Amount { get; set; }
        public string New_Product_Type { get; set; }
        public string New_Product_Model_No { get; set; }
        public Nullable<System.DateTime> Inv_Date { get; set; }
        public string invoiceURL { get; set; }
        public string ProductCondition { get; set; }
        public string ZohoSponsorOrderId { get; set; }
        public string StoreCode { get; set; }
        public string SponsorOrderNumber { get; set; }
        public string EstimatedDeliveryDate { get; set; }
        public string Size { get; set; }
        public string VoucherStatusName { get; set; }
        public Nullable<int> VoucherStatusId { get; set; }
        public Nullable<bool> IsVoucherused { get; set; }
    }
}
