//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCEL.DocUpload.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ExchangWithQC
    {
        public int OrderTransId { get; set; }
        public Nullable<int> OrderType { get; set; }
        public Nullable<int> ExchangeId { get; set; }
        public Nullable<int> ABBRedemptionId { get; set; }
        public string SponsorOrderNumber { get; set; }
        public string RegdNo { get; set; }
        public Nullable<decimal> ExchangePrice { get; set; }
        public Nullable<decimal> QuotedPrice { get; set; }
        public Nullable<decimal> Sweetner { get; set; }
        public Nullable<decimal> FinalPriceAfterQC { get; set; }
        public Nullable<int> EVCPriceMasterId { get; set; }
        public Nullable<decimal> EVCPrice { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> OrderQCId { get; set; }
        public Nullable<int> Expr1 { get; set; }
        public Nullable<System.DateTime> ProposedQCDate { get; set; }
        public string QCComments { get; set; }
        public string QualityAfterQC { get; set; }
        public Nullable<decimal> PriceAfterQC { get; set; }
        public Nullable<System.DateTime> Expr2 { get; set; }
        public int Id { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> CustomerDetailsId { get; set; }
        public Nullable<int> ProductTypeId { get; set; }
        public Nullable<int> BrandId { get; set; }
        public string Bonus { get; set; }
        public string Expr3 { get; set; }
        public string EstimatedDeliveryDate { get; set; }
        public string ProductCondition { get; set; }
        public Nullable<int> LoginID { get; set; }
        public string ExchPriceCode { get; set; }
        public Nullable<bool> Expr4 { get; set; }
        public Nullable<int> Expr5 { get; set; }
        public Nullable<System.DateTime> Expr6 { get; set; }
        public Nullable<System.DateTime> Expr7 { get; set; }
        public Nullable<bool> IsDtoC { get; set; }
        public string Expr8 { get; set; }
        public Nullable<int> BusinessPartnerId { get; set; }
        public string SaleAssociateName { get; set; }
        public string SaleAssociateCode { get; set; }
        public string PurchasedProductCategory { get; set; }
        public Nullable<bool> IsDelivered { get; set; }
        public string StoreCode { get; set; }
        public string VoucherCode { get; set; }
        public Nullable<bool> IsVoucherused { get; set; }
        public string SalesAssociateEmail { get; set; }
        public string SalesAssociatePhone { get; set; }
        public string InvoiceImageName { get; set; }
        public Nullable<System.DateTime> VoucherCodeExpDate { get; set; }
        public Nullable<decimal> Expr9 { get; set; }
        public string ProductNumber { get; set; }
        public Nullable<int> NewProductCategoryId { get; set; }
        public Nullable<int> NewProductTypeId { get; set; }
        public Nullable<int> NewBrandId { get; set; }
        public Nullable<int> ModelNumberId { get; set; }
        public string InvoiceNumber { get; set; }
        public string QCDate { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public Nullable<int> Expr10 { get; set; }
        public string Comment1 { get; set; }
        public string Comment2 { get; set; }
        public string Comment3 { get; set; }
        public string IsUnInstallationRequired { get; set; }
    }
}
