//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCEL.DocUpload.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZohoExchangeData
    {
        public int SponsorDataId { get; set; }
        public Nullable<bool> IsDataTransfered { get; set; }
        public string Errorlog { get; set; }
        public string Regd_No { get; set; }
        public string Sponsor_Order_No { get; set; }
        public string Order_Type { get; set; }
        public string Cust_Name { get; set; }
        public string Cust_E_mail { get; set; }
        public string Cust_Mobile { get; set; }
        public string Cust_Declared_Qlty { get; set; }
        public Nullable<double> Base_Exch_Value__Q_ { get; set; }
        public string Exch__Prod_Group { get; set; }
        public string Old_Prod_Type { get; set; }
        public string Model_No { get; set; }
        public string New_Price { get; set; }
        public string Invoice_Date { get; set; }
        public Nullable<double> Bonus { get; set; }
        public string C_Product_Group { get; set; }
        public string Product_Type { get; set; }
        public string Cust_Add_1 { get; set; }
        public string Cust_Add_2 { get; set; }
        public Nullable<double> Cust_Pin_Code { get; set; }
        public string Cust_City { get; set; }
        public string Cust_State { get; set; }
        public string Landmark { get; set; }
        public string New_Prod__Group { get; set; }
        public string New_Prod_Type { get; set; }
        public string New_Brand { get; set; }
        public string New_Size { get; set; }
        public string ABB_Fees { get; set; }
        public string EVC_Status { get; set; }
        public string Order_Flag { get; set; }
        public string E_Mail__SMS_Flag { get; set; }
        public string QC_Flag { get; set; }
        public string Installation_Flag { get; set; }
        public string Pickup_Flag { get; set; }
        public string Payment_Flag { get; set; }
        public string EVC_Drop_Flag { get; set; }
        public string Posting_Flag { get; set; }
        public string ABB_Plan_Name { get; set; }
        public string ABB_Plan_Period__Months_ { get; set; }
        public string Mode { get; set; }
        public string Amount_Payable_Through__LGC { get; set; }
        public string Old_Brand { get; set; }
        public Nullable<System.DateTime> Estimate_Delivery_Date_ { get; set; }
        public string Latest_Status { get; set; }
        public string Order_Date { get; set; }
        public string Pickup_Date { get; set; }
        public string Secondary_Order_Flag { get; set; }
        public string Status_Reason { get; set; }
        public string Actual_Amount_Paid { get; set; }
        public Nullable<System.DateTime> Expected_Pickup_Date { get; set; }
        public string Actual_Pickup_Date { get; set; }
        public string LGC_Tkt_No { get; set; }
        public string Size { get; set; }
        public string Ready_For_Logistic_Ticket { get; set; }
        public string Added_Time { get; set; }
        public string Pic_1 { get; set; }
        public string Pic_2 { get; set; }
        public string Pic_3 { get; set; }
        public string Pic_4 { get; set; }
        public string Invoice_Image { get; set; }
        public string ID { get; set; }
        public string Is_Deferred { get; set; }
        public string Is_Voucher_Redeemed { get; set; }
        public string Voucher_Code { get; set; }
        public string Voucher_Redeem_Date { get; set; }
        public string Voucher_Amount { get; set; }
        public string Purchased_Product { get; set; }
        public string Purchased_Product_Model { get; set; }
        public string Store_Name_For_Purchased_Product { get; set; }
        public string Logistic_By { get; set; }
        public string Upload_Date___Time { get; set; }
        public string Sponsor_Name { get; set; }
        public string Associate_Email { get; set; }
        public string Store_Status { get; set; }
        public string Purchased_Product_Category { get; set; }
        public string Store_Code { get; set; }
        public string Associate_Name { get; set; }
        public string Associate_Code { get; set; }
        public string Store_Phone_Number { get; set; }
        public string Last_Name { get; set; }
        public string Cust_1st_Name { get; set; }
        public string Customer_Declared_Age { get; set; }
        public string Is_DtoC { get; set; }
        public Nullable<double> Base_Exch_Value__P_ { get; set; }
        public Nullable<double> Base_Exch_Value__R_ { get; set; }
        public Nullable<double> Base_Exch_Value__S_ { get; set; }
        public Nullable<double> EVC_P { get; set; }
        public Nullable<double> EVC_Q { get; set; }
        public Nullable<double> EVC_R { get; set; }
        public Nullable<double> EVC_S { get; set; }
        public string Prod__Sr__No_ { get; set; }
        public string HSN_Code__For_ABB_Fees_ { get; set; }
        public string Invoice_No { get; set; }
        public string Price_Start_Date { get; set; }
        public string Price_End_Date { get; set; }
        public string ABB__ { get; set; }
        public string Exchange__ { get; set; }
        public string Exchange_Status { get; set; }
        public string Sponsor_Prog__code { get; set; }
        public string Exch__Price_ID { get; set; }
        public string ABB_Price_ID { get; set; }
        public string Reason_For_Cancellation { get; set; }
        public string First_Attempt_Date { get; set; }
        public string Record_Status { get; set; }
        public string Invoice_Posted { get; set; }
        public string E_Mail_SMS_Date { get; set; }
        public string QC_Date { get; set; }
        public string Installation_Date { get; set; }
        public string Payment_Date { get; set; }
        public string EVC_Drop_Date { get; set; }
        public string Posting_Date { get; set; }
        public string Latest_Date___Time { get; set; }
        public string Closed { get; set; }
        public string SVC_s_Call_No { get; set; }
        public Nullable<double> Total_Quote_P { get; set; }
        public Nullable<double> Total_Quote_Q { get; set; }
        public Nullable<double> Total_Quote_R { get; set; }
        public Nullable<double> Total_Quote_S { get; set; }
        public string Actual_Type { get; set; }
        public string Actual_Brand { get; set; }
        public string Prod_Sr_No { get; set; }
        public string Compressor_No_ODU_Sr_No { get; set; }
        public string pdf_file_for_QC { get; set; }
        public string QC_Comment { get; set; }
        public string Preferred_Time_For_QC { get; set; }
        public string Preferred_QC_Date_and_Time { get; set; }
        public string Actual_Size { get; set; }
        public string Actual_Prod_Qlty__at_time_of_QC_ { get; set; }
        public string Actual_Age { get; set; }
        public string Proof_Of_Delivery { get; set; }
        public string Actual__Total__Amount_as_per_QC { get; set; }
        public Nullable<double> Actual_Base_Amount_As_per__QC_ { get; set; }
        public string Actual_EVC_Amount_As_Per_QC { get; set; }
        public string Cust_OK_for_Price { get; set; }
        public string Logistic_Pic_1 { get; set; }
        public string Logistic_Pic_2 { get; set; }
        public string Logistic_Pic_3 { get; set; }
        public string Logistic_Pic_4 { get; set; }
        public string Cust_Declaration { get; set; }
        public string QC_by_LGC__Revise_EVC_Code { get; set; }
        public string EVC_Acknowledge { get; set; }
        public string Payment_To_Customer { get; set; }
        public string logistics_Bonus { get; set; }
        public string Lgc_Tkt_Created_Date { get; set; }
        public Nullable<double> Actual_Amt_payable__incl_Bonus_ { get; set; }
        public string Bank_Reference_ { get; set; }
        public string Date_paid { get; set; }
        public string Logistics_Status_Remark { get; set; }
        public string Pickup_Priority { get; set; }
        public string Nature_of_Complaint { get; set; }
        public string Is_Under_Warranty { get; set; }
    }
}
